# Generated by Django 5.1.7 on 2025-03-26 18:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_fileshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='shared_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 26, 18, 19, 54, 980369, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ExpiringLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=70, unique=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 3, 26, 19, 19, 54, 980369, tzinfo=datetime.timezone.utc))),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.file')),
            ],
        ),
    ]
