# Generated by Django 5.1.7 on 2025-03-26 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_fileshare_shared_at_expiringlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringlink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 26, 19, 21, 10, 569925, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='shared_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
